### ISSUE TITLE
[Q] Lack of comment on tools used

### ISSUE THREAD

**Issue by vlad2305m** [nickbailey/Kdenlive-3D-tools#1]
"There's a windows executable I'm using to decode the dependent stream in to a stand-alone file"

I'd like to (.bat) automate the processing of 3d tape. Which executable are you using? (I only found one - 3dtv)

Thanks for the work!

**Comment by nickbailey** [comment]
On Tuesday, 5 October 2021 18:58:53 BST vlad2305m wrote:
> "There's a windows executable I'm using to decode the dependent stream in to
> a stand-alone file"
> 
> I'd like to (.bat) automate the processing of 3d tape. Which executable are
> you using? (I only found two - idealshare and 3dtv, and both are GUI)
> 
> Thanks for the work!

I got nowhere with it although it did run under Wine. I think it was some sort 
of Intel video toolkit demo program which a DOS guy had wrapped, and released 
binary only. So no thanks to me I'm afraid. I think we do need some sort of 3D 
demux on planet Linux but I don't have time to look at it, and since I work in 
a EE dept, only teaching CS postgrads very occasionally, the chances of 
getting any of them to pitch in and produce something useful is close to zero 
:(

IIRC there was an open source version of the toolkit, but it had no 3D 
support.

This is all very much out of date info, so YYMV. Do let me know if you come 
across anything useful, or want me to dig around a but further for more info 
on the MS executable.

Nick/.
